#![allow(dead_code)]

[package]
name = "rust_experiments"
version = "0.1.0"
authors = ["Nikita Petrenko <npetrenko97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
